### PR TITLE
Version4

### PR DESCRIPTION
**Pull request by enagoshi**

### CODE REVIEW

**Comment by koluke** [comment]
👀

**Comment by enagoshi** [comment]
Is it possible to publish this to self-service before school starts? 'Iolani starts on Aug 20.

**Comment by koluke** [comment]
It should be, but it looks like there's some conflicts that need to be resolved before we can merge this into master/deploy to Self Service.  That and with the sheer volume of changes I hope nothing breaks.

**Review by koluke — APPROVED** [review]
Lot of changes, but looks like everything works okay

**Pull request merged**
